package com.melberry.utils

enum class OnboardingStateValue {
    ONBOARDING_REAL_TIME,
    ONBOARDING_FILTER,
    ONBOARDING_PRICE_AND_RESTRICTIONS,
    ONBOARDING_DISABILITIES,
    ONBOARDING_CHOOSE_CITY
}
